### PR TITLE
move all code from g-cpan -> App::gcpan

### PR DESCRIPTION
**Pull request by bor**
This is allow us to keep the code more maintainable!
(under tests, coverage, etc)

### CODE REVIEW

**Comment by bor** [comment]
@kentfredric , @akhuettel
would be nice to get any feedback

**Comment by akhuettel** [comment]
Well, it looks like a reasonable plan to me...

**Comment by bor** [comment]
Introduced a light version in #41

**Comment by bor** [comment]
I'm going to 'slow moving' strategy to avoid possible breaks.

**Pull request closed without merging**
